services:
  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}-wordpress
    ports: !override []
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DEBUG: "false"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
        define('DISALLOW_FILE_EDIT', true);
        define('WP_AUTO_UPDATE_CORE', false);
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - wp-uploads:/var/www/html/wp-content/uploads
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default
      - nginx-proxy-network
    restart: unless-stopped

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    ports: !override []
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
    restart: unless-stopped

networks:
  nginx-proxy-network:
    external: true
